from django.urls import path    # type: ignore
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.urls import re_path
from HomePage import views, chat_views

urlpatterns = [
    path('', views.home, name='home'),
    path('api/chat/', chat_views.chat_completions, name='chat_completions'),
    path('api/chat/stream/', chat_views.chat_stream, name='chat_stream'),
    path('chat/', views.chat_page, name='chat_page'),
    path('about/', views.about, name='about'),
    path('history/', views.roots, name='history'),
    path('user/register/', views.user_register_view, name='user_register'),
    path('user/login/', views.user_login_view, name='user_login'),
    path('user/logout/', views.user_logout_view, name='user_logout'),
    path('roots/', views.history, name='roots'),
    path('scc-history/', views.scchistory, name='scc-history'),
    path('MFG/', views.MFG, name='MFG'),
    path('about/', views.about, name='about'),
    # SE/* routes now handled by React SPA - see backend/urls.py react_urlpatterns
    # Keeping these commented for reference in case we need to restore specific endpoints
    # path('SE/PD/', views.manage_dashboard, name='manage_dashboard'),
    # path('SE/PD/property/add/', views.add_property, name='add_property'),
    # path('SE/PD/property/<str:reference_number>/edit/', views.edit_property, name='edit_property'),
    # path('SE/PD/property/<str:reference_number>/delete/', views.delete_property, name='delete_property'),
    # path('SE/PD/property/<str:reference_number>/images/', views.manage_images, name='manage_images'),
    # path('SE/PD/property/<str:reference_number>/images/delete/<int:image_id>/', views.delete_property_image, name='delete_property_image'),
    # path('SE/PD/property/<str:reference_number>/quick-edit/', views.quick_edit_field, name='quick_edit_field'),
    # path('SE/PD/property/<str:reference_number>/approve/', views.approve_property, name='approve_property'),
    # path('SE/PD/property/<str:reference_number>/deny/', views.deny_property, name='deny_property'),
    # path('SE/Profile/', views.profile, name='profile'),
    # path('SE/Clients/', views.clients_list, name='clients_list'),
    # path('SE/leadership/', views.se_leadership, name='se-leadership'),
    # path('SE/contact/', views.se_contact, name='se-contact'),
    # path('SE/process/', views.se_process, name='se-process'),
    # path('SE/replacement/', views.se_replacement, name='se-replacement'),
    # path('SE/Assets/', views.se_Assets, name='se-Assets'),
    # path('SE/identified/', views.se_identified, name='se-identified'),
    # path('SE/partners/', views.se_partners, name='se-partners'),
    # path('SE/Sins/', views.se_Sins, name='se_Sins'),
    # path('SE/DST-Process/', views.dst_process, name='dst_process'),
    # path('SE/US-v-THEM/', views.us_vs_them, name='us_vs_them'),
    # path('SE/IRS/', views.se_IRS, name='se-IRS'),
    # path('SE/Alpha/', views.se_Alpha, name='se-Alpha'),
    # path('SE/Pure/', views.se_Pure, name='se-Pure'),
    # path('SE/OwnDeed/', views.se_OwnDeed, name='se-OwnDeed'),
    # path('SE/Newsletter/', views.se_Newsletter, name='se-Newsletter'),
    # path('SE/Blog/', views.se_Blog, name='se-Blog'),
    # path('SE/Dashboard/', views.se_Dashboard, name='se-Dashboard'),
    # path('SE/Shelf/', views.se_Shelf, name='se-Shelf'),
    # path('SE/enrollment/', views.create_exchange_id, name='create_exchange_id'),
    # path('SE/exchange-ids/', views.list_exchange_ids, name='list_exchange_ids'),
    # path('SE/api/like-property/', views.like_property, name='like_property'),
    # path('SE/api/unlike-property/', views.unlike_property, name='unlike_property'),
    # path('SE/api/user-likes/', views.get_user_likes, name='get_user_likes'),
    # path('SE/api/user-exchange-ids/', views.get_user_exchange_ids, name='get_user_exchange_ids'),
    path('advisoryboard/', views.advisoryboard, name='advisoryboard'),
    path('foradvisors/', views.foradvisors, name='foradvisors'),
    path('sign-form/', views.user_form_view, name='sign_form'),
    path('lease-agreement/', views.lease_agreement_form_view, name='lease_agreement_form'),
    path('lease-agreement-notary/', views.lease_agreement_notary_form_view, name='lease_agreement_notary_form'),
    path('SA/', views.SA, name='SA'),
    path('SA/focus/', views.focus, name='focus'),
    path('SA/verticals/', views.verticals, name='verticals'),
    path('SA/dealflow/', views.dealflow, name='dealflow'),
    path('SA/serve/', views.SA_serve, name='serve'),
    path('SCC/', views.SCC, name='SCC'),
    path('SCC/partnership/', views.partnership, name='partnership'),
    path('who-we-serve/', views.SCC_serve, name='SCC-serve'),
    path('SCC/verticals/', views.SCC_verticals, name='SCC-verticals'),
    path('SCC/organic/', views.SCC_organic, name='SCC-organic'),
    path('SM/', views.SM, name='SM'),
    path('onboarding/', views.smonboarding, name='SM-onboarding'),
    path('services/', views.smservices, name='SM-services'),
    path('tools/', views.smtools, name='SM-tools'),
    path('SSP/', views.SSP, name='SSP'),
    path('SBRI/', views.SBRI, name='SBRI'),
    path('SBRO/', views.SBRO, name='SBRO'),
    path('SC/', views.SC, name='SC'),
    path('SCA/', views.SCA, name='SCA'),
    # path('SE/', views.SE, name='SE'),  # Now handled by React SPA
    # path('SE/Basics', views.SE_basics, name='SE-Basics'),
    # path('SE/How', views.SE_How, name='SE-How'),
    path('organization/', views.organization, name='organization'),
    path('investors/', views.investors_view, name='sc-investors'),
    path('borrowers/', views.borrowers_view, name='sc-borrowers'),
    path('loans/', views.loans_view, name='sc-loans'),
    path('mca/', views.mca_view, name='sc-mca'),
    path('rtl/', views.rtl_view, name='sc-rtl'),
    path('cbl/', views.cbl_view, name='sc-cbl'),
    path('preferredequity/', views.preferredequity_view, name='sc-preferredequity'),
    path('leasing/', views.leasing_view, name='sc-leasing'),
    path('bridge-loan/', views.bridge_loan, name='sc-bridge-loan'),
    path('construction-loan/', views.construction_loan, name='sc-construction-loan'),
    path('dscr-loan/', views.dscr_loan, name='sc-dscr-loan'),
    path('fixflip-loan/', views.fixflip_loan, name='sc-fixflip-loan'),
    path('SSE/', views.SSE, name='SSE'),
    path('fmf/', views.fmf, name='fmf'),
    path('fmf/states/', views.states, name='states'),
    path('fmf/cases/', views.cases, name='cases'),
    path('fmf/howitworks/', views.howitworks, name='howitworks'),
    path('fmc/', views.fmc, name='fmc'),
    path('fmi/', views.fmi, name='fmi'),
    path('fml/', views.fml, name='fml'),
    path('qoz/', views.qoz, name='qoz'),
    path('core/', views.core, name='core'),
    path('axcs/', views.axcs, name='axcs'),
    path('appraisal/', views.appraisal, name='appraisal'),
    path('NE/About/', views.NEAbout, name='NEAbout'),
    path('macro-economic-data/', views.macro_economic_data, name='macro-economic-data'),
    path('api/fred-rates/', views.get_fred_rates, name='get_fred_rates'),
    path('error/', views.error, name='error'),
    path('contact/', views.contact, name='contact'),
    path('news/', views.news, name='news'),
    path('temp/', views.temp, name='temp'),
    path('standards/', views.standards, name='standards'),
    path('leadership/', views.leadership, name='leadership'),
    path('businessheads/', views.businessheads, name='businessheads'),
    path('edgeleadership/', views.edgeleadership, name='edgeleadership'),
    path('edgeabout/', views.edgeabout, name='edgeabout'),
    path('investmentmerits/', views.investmentmerits, name='investmentmerits'),
    path('organizationoverview/', views.organizationoverview, name='organizationoverview'),
    path('brokerdealers/', views.brokerdealers, name='brokerdealers'),
    path('HNWIs/', views.HNWIs, name='HNWIs'),
    path('institutional-investors/', views.institutional, name='institutional-investors'),
    path('wealthadvisorRIAs/', views.wealthadvisorRIAs, name='wealthadvisorRIAs'),
    path('CRE/', views.CRE, name='CRE'),
    path('RRE/', views.RRE, name='RRE'),
    path('LRE/', views.LRE, name='LRE'),
    path('AI/', views.AI, name='AI'),
    path('LitFi/', views.LitFi, name='LitFi'),
    path('MF/', views.MF, name='MF'),
    path('SCOM/', views.SCOM, name='SCOM'),
    path('disclosure/', views.disclosure, name='disclosure'),
    path('legal/', views.legal, name='legal'),
    path('privacy/', views.privacy, name='privacy'),
    path('phishing/', views.phishing, name='phishing'),
    path('personaldata/', views.personaldata, name='personaldata'),
    path('datacenters/', views.datacenters, name='datacenters'),
    path('SCOL/', views.SCOL, name='SCOL'),
    path('PE/', views.PE, name='PE'),
    path('success/', views.success_form, name='success_form'),
    path('forms/', views.forms, name='forms'),
    path('unavailable/', views.unavailable, name='unavailable'),
    path('SF/', views.SF, name='SF'),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/', views.file_list, name='file_list'),
    path('cookies/', views.cookies, name='cookies'),
    path('termsofuse/', views.termsofuse, name='termsofuse'),
    path('personalinfo/', views.personalinfo, name='personalinfo'),
    path('accessibility/', views.accessibility, name='accessibility'),
    path('sponsor/', views.sponsor, name='sponsor'),
    # path('SE/Hub/', views.SE_Hub, name='SE-Hub'),  # Now handled by React SPA
    path('terms/', views.terms, name='terms'),
    # path('SE/deal-detail/<str:reference_number>/', views.dealdetail, name='SE-deal-detail'),  # Now handled by React SPA
    path('api/properties/', views.api_properties, name='api_properties'),
    path('api/properties/<str:reference_number>/', views.api_property_detail, name='api_property_detail'),
    path('dealsubmission/', views.dealsubmission, name='dealsubmission'),
    path('dealsubmissionform/', views.dealsubmissionform, name='dealsubmissionform'),
    path('file/delete/<int:file_id>/', views.delete_file, name='delete_file'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('contact/submit/', views.contact_submit, name='contact_submit'),
    path('access-request/submit/', views.access_request_submit, name='access_request_submit'),
    # path('SE/enrollment/submit/', views.enrollment_submit, name='enrollment_submit'),  # Now handled by React SPA
    path('api/pipeline_properties/', views.api_pipeline_properties, name='api_pipeline_properties'),
    # path('SE/Pipe/', views.SE_pipeline, name='SE_pipeline'),  # Now handled by React SPA
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    re_path(r'^robots\.txt$', serve, {'path': 'robots.txt', 'document_root': settings.STATICFILES_DIRS[0], }),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Serve media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
