# Generated by Django 5.1.7 on 2025-10-30 20:44

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseAgreementNotaryRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("document_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Commercial Lease - Notary",
                "verbose_name_plural": "Commercial Lease - Notary",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaseAgreementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("document_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Commercial Lease - No Notary",
                "verbose_name_plural": "Commercial Lease - No Notary",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NDARequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("reason", models.CharField(default="Not specified", max_length=255)),
                ("document_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "NDA Request",
                "verbose_name_plural": "NDA Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "property_header",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short subtitle/header (max 150 characters)",
                        max_length=150,
                    ),
                ),
                ("address", models.TextField()),
                ("property_type", models.CharField(max_length=50)),
                (
                    "strategies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Up to 4 value-add strategies",
                    ),
                ),
                (
                    "marketing_title",
                    models.CharField(
                        blank=True,
                        help_text="Hero marketing title (3-6 words)",
                        max_length=100,
                    ),
                ),
                (
                    "hero_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated marketing summary"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured deal on homepage"
                    ),
                ),
                (
                    "loi_date",
                    models.DateField(blank=True, null=True, verbose_name="LOI Date"),
                ),
                (
                    "psa_date",
                    models.DateField(blank=True, null=True, verbose_name="PSA Date"),
                ),
                (
                    "dd_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Due Diligence End Date"
                    ),
                ),
                ("close_date", models.DateField(verbose_name="Closing Date")),
                (
                    "deal_stage",
                    models.CharField(
                        choices=[
                            ("LOI_OUT", "LOI OUT"),
                            ("LOI_NEGOTIATING", "LOI Received & Negotiating"),
                            ("LOI_ACCEPTED", "LOI Accepted Initiating Legal"),
                            ("CONTRACT_NEGOTIATION", "Contract Negotiation"),
                            ("CONTRACT_SIGNED", "Contract Signed"),
                            (
                                "IN_DUE_DILIGENCE",
                                "Soft Deposit Wired, In Due Diligence",
                            ),
                        ],
                        default="LOI_OUT",
                        help_text="Current stage of the deal",
                        max_length=50,
                    ),
                ),
                ("total_sf", models.IntegerField(verbose_name="Total Square Feet")),
                ("acres", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_units", models.IntegerField()),
                (
                    "vacancy_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Vacancy %"
                    ),
                ),
                ("vacant_sf", models.IntegerField(verbose_name="Vacant Square Feet")),
                (
                    "walt",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="WALT (Years)"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, help_text="City", max_length=100),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State abbreviation", max_length=2
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, help_text="ZIP code", max_length=10),
                ),
                (
                    "submarket",
                    models.CharField(
                        blank=True,
                        help_text="Auto-filled by Google Maps",
                        max_length=200,
                    ),
                ),
                (
                    "location_highlights",
                    models.TextField(blank=True, help_text="Key location advantages"),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "cap_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Cap Rate %"
                    ),
                ),
                (
                    "current_noi",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Current NOI"
                    ),
                ),
                ("debt_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Interest Rate %"
                    ),
                ),
                (
                    "dscr",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="DSCR"
                    ),
                ),
                ("total_equity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ltv", models.IntegerField(verbose_name="LTV %")),
                (
                    "est_annual_cash_flow",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Estimated Annual Cash Flow",
                    ),
                ),
                (
                    "per_100k",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Cash Flow Per $100k",
                    ),
                ),
                (
                    "est_cash_on_cash",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Estimated Cash-on-Cash %",
                    ),
                ),
                (
                    "distribution_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Semi-Annually", "Semi-Annually"),
                            ("Annually", "Annually"),
                            ("At Exit", "At Exit"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "num_tenants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Tenants"
                    ),
                ),
                (
                    "occupancy_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Occupancy %",
                    ),
                ),
                (
                    "lease_structure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Gross", "Gross"),
                            ("Modified Gross", "Modified Gross"),
                            ("NNN", "NNN"),
                            ("Mixed", "Mixed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("tenant_1_name", models.CharField(blank=True, max_length=200)),
                (
                    "tenant_1_sf",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tenant 1 SF Leased"
                    ),
                ),
                (
                    "tenant_1_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% of NRA",
                    ),
                ),
                (
                    "tenant_1_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Lease Expiry"
                    ),
                ),
                (
                    "tenant_1_guarantee",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Corporate/Personal Guarantee",
                    ),
                ),
                ("tenant_2_name", models.CharField(blank=True, max_length=200)),
                (
                    "tenant_2_sf",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tenant 2 SF Leased"
                    ),
                ),
                (
                    "tenant_2_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% of NRA",
                    ),
                ),
                (
                    "tenant_2_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Lease Expiry"
                    ),
                ),
                (
                    "tenant_2_guarantee",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Corporate/Personal Guarantee",
                    ),
                ),
                ("tenant_3_name", models.CharField(blank=True, max_length=200)),
                (
                    "tenant_3_sf",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tenant 3 SF Leased"
                    ),
                ),
                (
                    "tenant_3_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% of NRA",
                    ),
                ),
                (
                    "tenant_3_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Lease Expiry"
                    ),
                ),
                (
                    "tenant_3_guarantee",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Corporate/Personal Guarantee",
                    ),
                ),
                (
                    "business_plan",
                    models.TextField(
                        blank=True, help_text="Value-add strategy and exit plan"
                    ),
                ),
                (
                    "kbi_1",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Key Business Initiative #1",
                    ),
                ),
                (
                    "kbi_2",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Key Business Initiative #2",
                    ),
                ),
                (
                    "kbi_3",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Key Business Initiative #3",
                    ),
                ),
                (
                    "kbi_4",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Key Business Initiative #4",
                    ),
                ),
                (
                    "current_funding",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("max_investors", models.IntegerField()),
                ("current_investors", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_pipeline", models.BooleanField(default=False)),
                (
                    "projected_irr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Projected IRR percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "hold_period_years",
                    models.IntegerField(
                        default=5, help_text="Expected hold period in years"
                    ),
                ),
                (
                    "broker_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "broker_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "broker_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "broker_company",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("broker_notes", models.TextField(blank=True, default="")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Internal deal notes and comments"
                    ),
                ),
                (
                    "completion_percentage",
                    models.IntegerField(default=0, help_text="Form completion %"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="draft",
                        help_text="Approval status of the property",
                        max_length=20,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When property was submitted for review",
                        null=True,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When property was reviewed", null=True
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about approval/denial"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SimpleEXCHANGE - Deal",
                "verbose_name_plural": "SimpleEXCHANGE - Deals",
                "ordering": ["-close_date"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee_type", models.CharField(max_length=50)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="HomePage.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Fee",
                "verbose_name_plural": "Property Fees",
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("order", models.IntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="HomePage.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "SimpleEXCHANGE - Image",
                "verbose_name_plural": "SimpleEXCHANGE - Images",
                "ordering": ["property", "order"],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("lead_referrer", "Lead Referrer"),
                            ("property_broker", "Property Broker"),
                        ],
                        default="client",
                        help_text="User classification and permission level",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("om", "Offering Memorandum"),
                            ("rentroll", "Rent Roll"),
                            ("proforma", "Pro Forma"),
                            ("tic", "TIC Agreement"),
                            ("environmental", "Environmental Report"),
                            ("legal", "Legal Opinion"),
                            ("operating", "Operating Statements"),
                            ("market", "Market Research"),
                            ("brochure", "Marketing Brochure"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="property_documents/")),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="HomePage.property",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Document",
                "verbose_name_plural": "Property Documents",
                "ordering": ["document_type", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyBrokerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated broker ID (e.g., PB-000001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("license_state", models.CharField(blank=True, max_length=2)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default commission rate percentage",
                        max_digits=5,
                    ),
                ),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_routing_number", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "property_broker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_broker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Broker Profile",
                "verbose_name_plural": "Property Broker Profiles",
                "ordering": ["broker_id"],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="broker_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Property Broker who submitted this property",
                limit_choices_to={"user_type": "property_broker"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brokered_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed this property",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted this property",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LeadReferrerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referrer_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated referrer ID (e.g., LR-000001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default commission rate percentage",
                        max_digits=5,
                    ),
                ),
                ("bank_account_name", models.CharField(blank=True, max_length=200)),
                ("bank_account_number", models.CharField(blank=True, max_length=50)),
                ("bank_routing_number", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "lead_referrer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_referrer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Referrer Profile",
                "verbose_name_plural": "Lead Referrer Profiles",
                "ordering": ["referrer_id"],
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated sequential ID (e.g., C-000001)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "client_alias",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Display alias (e.g., JOHND3826)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("investment_thesis", models.TextField(blank=True, null=True)),
                ("financial_goals", models.TextField(blank=True, null=True)),
                (
                    "risk_reward",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
                "ordering": ["client_id"],
            },
        ),
        migrations.CreateModel(
            name="ChatUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("first_message_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("email_sent_at_15", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="User's email address", max_length=254),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sale price of relinquished asset",
                        max_digits=12,
                    ),
                ),
                (
                    "equity_rollover",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Equity rollover for replacement 1031 asset",
                        max_digits=12,
                    ),
                ),
                ("closing_date", models.DateField(help_text="Relinquish closing date")),
                (
                    "qi_name",
                    models.CharField(
                        blank=True,
                        help_text="Qualified Intermediary name",
                        max_length=200,
                    ),
                ),
                (
                    "needs_qi_referral",
                    models.BooleanField(
                        default=False, help_text="Does user need QI referral?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of submission", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="Browser user agent"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="Property they're interested in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="HomePage.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked user account (if created)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Enrollment",
                "verbose_name_plural": "Property Enrollments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="HomePage_pr_email_b8ef0b_idx"),
                    models.Index(
                        fields=["created_at"], name="HomePage_pr_created_92aae3_idx"
                    ),
                    models.Index(
                        fields=["property"], name="HomePage_pr_propert_e84d87_idx"
                    ),
                ],
            },
        ),
    ]
