# Generated by Django 5.1.6 on 2025-11-18 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated exchange ID (e.g., E-1004-01)', max_length=20, unique=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price of relinquished property', max_digits=12, null=True)),
                ('equity_rollover', models.DecimalField(blank=True, decimal_places=2, help_text='Equity to rollover', max_digits=12, null=True)),
                ('closing_date', models.DateField(blank=True, help_text='Expected closing date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exchange ID',
                'verbose_name_plural': 'Exchange IDs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Like',
                'verbose_name_plural': 'Property Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='propertyenrollment',
            name='closing_date',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='User who added this client (Staff/Admin/Referrer)', limit_choices_to={'user_type__in': ['admin', 'staff', 'lead_referrer']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='equity_rollover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='have_qi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='qi_company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='relinquish_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='broker_cell',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Broker Cell Phone'),
        ),
        migrations.AddField(
            model_name='property',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission %'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenancy_hero',
            field=models.TextField(blank=True, default='', help_text='Additional comments for tenancy section', verbose_name='Tenancy Hero Comments'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_1_lease_structure',
            field=models.CharField(blank=True, choices=[('Gross', 'Gross'), ('Modified Gross', 'Modified Gross'), ('NN', 'NN'), ('NNN', 'NNN'), ('Mixed', 'Mixed')], max_length=50, verbose_name='Tenant 1 Lease Structure'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_2_lease_structure',
            field=models.CharField(blank=True, choices=[('Gross', 'Gross'), ('Modified Gross', 'Modified Gross'), ('NN', 'NN'), ('NNN', 'NNN'), ('Mixed', 'Mixed')], max_length=50, verbose_name='Tenant 2 Lease Structure'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_3_lease_structure',
            field=models.CharField(blank=True, choices=[('Gross', 'Gross'), ('Modified Gross', 'Modified Gross'), ('NN', 'NN'), ('NNN', 'NNN'), ('Mixed', 'Mixed')], max_length=50, verbose_name='Tenant 3 Lease Structure'),
        ),
        migrations.AddField(
            model_name='propertyenrollment',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='leadreferrerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_referrer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_structure',
            field=models.CharField(blank=True, choices=[('Gross', 'Gross'), ('Modified Gross', 'Modified Gross'), ('NN', 'NN'), ('NNN', 'NNN'), ('Mixed', 'Mixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['reference_number'], name='prop_ref_number_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', '-close_date'], name='prop_active_close_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'is_active'], name='prop_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'is_active'], name='prop_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['broker_user', '-created_at'], name='prop_broker_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_pipeline'], name='prop_pipeline_idx'),
        ),
        migrations.AddField(
            model_name='exchangeid',
            name='user',
            field=models.ForeignKey(help_text='User who owns this exchange ID', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertylike',
            name='exchange_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_properties', to='HomePage.exchangeid'),
        ),
        migrations.AddField(
            model_name='propertylike',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='HomePage.property'),
        ),
        migrations.AddField(
            model_name='propertylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exchangeid',
            index=models.Index(fields=['exchange_id'], name='HomePage_ex_exchang_7dce48_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeid',
            index=models.Index(fields=['user', '-created_at'], name='HomePage_ex_user_id_132d9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertylike',
            unique_together={('exchange_id', 'property')},
        ),
    ]
