# Generated by Django 5.1.7 on 2025-10-31 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who added this client (Staff/Admin/Referrer)",
                limit_choices_to={"user_type__in": ["admin", "staff", "lead_referrer"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
