# Generated by Django 5.1.7 on 2025-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0002_clientprofile_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="property_images/"
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
