# Generated by Django 5.1.7 on 2025-10-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0003_propertyimage_image_alter_propertyimage_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="image",
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image_url",
            field=models.URLField(),
        ),
    ]
