# Generated by Django 5.1.7 on 2025-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0004_remove_propertyimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyenrollment",
            name="closing_date",
        ),
        migrations.AddField(
            model_name="propertyenrollment",
            name="close_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
