# Generated by Django 5.1.7 on 2025-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0005_remove_propertyenrollment_closing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyenrollment",
            name="close_date",
            field=models.DateField(blank=True, null=True, verbose_name="Closing Date"),
        ),
    ]
