# Generated by Django 5.1.7 on 2025-11-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0006_alter_propertyenrollment_close_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="broker_cell",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Broker Cell Phone"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="commission",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Commission %",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tenancy_hero",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional comments for tenancy section",
                verbose_name="Tenancy Hero Comments",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tenant_1_lease_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gross", "Gross"),
                    ("Modified Gross", "Modified Gross"),
                    ("NN", "NN"),
                    ("NNN", "NNN"),
                    ("Mixed", "Mixed"),
                ],
                max_length=50,
                verbose_name="Tenant 1 Lease Structure",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tenant_2_lease_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gross", "Gross"),
                    ("Modified Gross", "Modified Gross"),
                    ("NN", "NN"),
                    ("NNN", "NNN"),
                    ("Mixed", "Mixed"),
                ],
                max_length=50,
                verbose_name="Tenant 2 Lease Structure",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="tenant_3_lease_structure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Gross", "Gross"),
                    ("Modified Gross", "Modified Gross"),
                    ("NN", "NN"),
                    ("NNN", "NNN"),
                    ("Mixed", "Mixed"),
                ],
                max_length=50,
                verbose_name="Tenant 3 Lease Structure",
            ),
        ),
    ]
