# Generated by Django 5.1.7 on 2025-11-06 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0007_property_broker_cell_property_commission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated exchange ID (e.g., E-1004-1)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "base_number",
                    models.IntegerField(
                        editable=False,
                        help_text="Global sequential number (e.g., 1004)",
                    ),
                ),
                (
                    "client_sequence",
                    models.IntegerField(
                        editable=False,
                        help_text="Sequential exchange number for this specific client (1, 2, 3...)",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sale price of relinquished asset",
                        max_digits=12,
                    ),
                ),
                (
                    "equity_rollover",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Equity rollover for replacement 1031 asset",
                        max_digits=12,
                    ),
                ),
                (
                    "relinquish_closing_date",
                    models.DateField(help_text="Closing date of relinquished property"),
                ),
                (
                    "has_qi",
                    models.BooleanField(
                        default=False,
                        help_text="Does the client have a QI?",
                        verbose_name="Has Qualified Intermediary",
                    ),
                ),
                (
                    "qi_company_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of Qualified Intermediary (if applicable)",
                        max_length=200,
                        verbose_name="QI Company Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        help_text="Current status of the exchange",
                        max_length=20,
                    ),
                ),
                (
                    "identification_deadline",
                    models.DateField(
                        blank=True,
                        help_text="45-day identification deadline (auto-calculated)",
                        null=True,
                    ),
                ),
                (
                    "exchange_deadline",
                    models.DateField(
                        blank=True,
                        help_text="180-day exchange completion deadline (auto-calculated)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client who owns this exchange",
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this exchange record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exchanges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange",
                "verbose_name_plural": "Exchanges",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeLikedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Client notes about this property for this exchange",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        help_text="Priority ranking (1 = highest priority)",
                        null=True,
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        help_text="The exchange this liked property belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_properties",
                        to="HomePage.exchange",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="The property that was liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_likes",
                        to="HomePage.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Liked Property",
                "verbose_name_plural": "Exchange Liked Properties",
                "ordering": ["exchange", "priority", "-liked_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exchange",
            index=models.Index(
                fields=["client", "-created_at"], name="HomePage_ex_client__d5a522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchange",
            index=models.Index(
                fields=["exchange_id"], name="HomePage_ex_exchang_4b243d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchange",
            index=models.Index(fields=["status"], name="HomePage_ex_status_d8004d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="exchange",
            unique_together={("client", "client_sequence")},
        ),
        migrations.AddIndex(
            model_name="exchangelikedproperty",
            index=models.Index(
                fields=["exchange", "-liked_at"], name="HomePage_ex_exchang_0d0e09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangelikedproperty",
            index=models.Index(
                fields=["property"], name="HomePage_ex_propert_ff075a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangelikedproperty",
            unique_together={("exchange", "property")},
        ),
    ]
