# Generated by Django 5.1.7 on 2025-11-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0009_remove_exchangelikedproperty_exchange_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="exchange_id",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="exchange_process_count",
        ),
    ]
