# Generated by Django 5.1.7 on 2025-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0010_remove_clientprofile_exchange_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="exchange_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated Exchange ID in format E-XXXX-Y",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="exchange_process_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Tracks number of exchange processes for this client",
            ),
        ),
    ]
