# Generated by Django 5.1.7 on 2025-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0011_clientprofile_exchange_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="equity_rollover",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="have_qi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="relinquish_closing_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
