# Generated by Django 5.1.7 on 2025-11-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "HomePage",
            "0012_clientprofile_equity_rollover_clientprofile_have_qi_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HomePage.clientprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HomePage.property",
                    ),
                ),
            ],
            options={
                "unique_together": {("client_profile", "property")},
            },
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="liked_properties",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_by_clients",
                through="HomePage.LikedProperty",
                to="HomePage.property",
            ),
        ),
    ]
