# Generated by Django 5.1.7 on 2025-11-06 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0013_likedproperty_clientprofile_liked_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="exchange_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Auto-generated Exchange ID for any user",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="leadreferrerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_referrer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
