# Generated by Django 5.1.7 on 2025-11-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0014_alter_clientprofile_exchange_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="liked_properties",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="exchange_id",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="exchange_process_count",
        ),
        migrations.CreateModel(
            name="ExchangeID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated exchange ID (e.g., E-1004-01)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Sale price of relinquished property",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "equity_rollover",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Equity to rollover",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, help_text="Expected closing date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this exchange ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_ids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange ID",
                "verbose_name_plural": "Exchange IDs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="LikedProperty",
        ),
        migrations.AddIndex(
            model_name="exchangeid",
            index=models.Index(
                fields=["exchange_id"], name="HomePage_ex_exchang_7dce48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeid",
            index=models.Index(
                fields=["user", "-created_at"], name="HomePage_ex_user_id_132d9d_idx"
            ),
        ),
    ]
