# Generated by Django 5.1.7 on 2025-11-12 15:36
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("HomePage", "0016_propertylike"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(default="", upload_to="property_images/"),
            preserve_default=False,
        ),
    ]
