# Generated by Django 5.2.8 on 2025-11-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0016_propertylike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lease_structure',
            field=models.CharField(blank=True, choices=[('Gross', 'Gross'), ('Modified Gross', 'Modified Gross'), ('NN', 'NN'), ('NNN', 'NNN'), ('Mixed', 'Mixed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['reference_number'], name='prop_ref_number_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_active', '-close_date'], name='prop_active_close_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'is_active'], name='prop_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'is_active'], name='prop_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['broker_user', '-created_at'], name='prop_broker_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_pipeline'], name='prop_pipeline_idx'),
        ),
    ]
