# Generated by Django 5.2.8 on 2025-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0018_merge_0017_add_property_indexes_and_manager_0017_remove_propertyimage_image_url_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
