# Generated by Django 5.1.5 on 2025-11-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HomePage", "0002_exchangeid_propertylike_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="qi_company_name",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="state",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="zip_code",
        ),
    ]
