# Generated by Django 5.1.6 on 2025-11-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0023_remove_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='closing_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total closing costs for the client enrollment.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='debt_payoff_at_closing',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Debt payoff amount at closing for the client enrollment.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='qi_company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
