# Generated by Django 5.1.6 on 2025-11-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0024_clientprofile_address_clientprofile_city_and_more'),
        ('HomePage', '002X_readd_clientprofile_fields'),
    ]

    operations = [
    ]
