# Generated by Django 5.2.8 on 2025-12-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0025_add_image_field_to_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeid',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When this exchange ID was claimed by a user', null=True),
        ),
        migrations.AddField(
            model_name='exchangeid',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Whether this exchange ID has been linked to a user account'),
        ),
        migrations.AlterField(
            model_name='exchangeid',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this exchange ID (nullable for pre-account generation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exchangeid',
            index=models.Index(fields=['is_claimed', 'created_at'], name='HomePage_ex_is_clai_3ce9ef_idx'),
        ),
    ]
